# Generated by Django 5.0.13 on 2025-04-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='firs_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
