# Generated by Django 5.0.13 on 2025-04-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_perfilusuario_descripcion_perfilusuario_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
