# Generated by Django 5.1.6 on 2025-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100, verbose_name='Grupo de Servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
