# Generated by Django 5.1.6 on 2025-03-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0002_gruposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecl', models.CharField(max_length=50, verbose_name='Nombre Centro Logístico')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupocliente', models.CharField(max_length=50, verbose_name='Nombre Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitcliente', models.BigIntegerField(verbose_name='NIT Cliente')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('grupocliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.grupoclientes', verbose_name='Grupo')),
            ],
        ),
    ]
