# Generated by Django 5.1.6 on 2025-03-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0004_alter_centrologistico_options_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100, verbose_name='Descripción Servicio')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.gruposervicio', verbose_name='Grupo de Servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
