# Generated by Django 5.1.6 on 2025-03-15 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0005_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.IntegerField(verbose_name='Tarifa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.clientes', verbose_name='Cliente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.gruposervicio', verbose_name='Grupo de Servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.servicios', verbose_name='Servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
