# Generated by Django 5.1.6 on 2025-03-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0006_tarifas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agregarservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('placa', models.CharField(blank=True, max_length=6, null=True, verbose_name='Placa')),
                ('tarifa', models.IntegerField(verbose_name='Tarifas')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('latitud', models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=10, null=True, verbose_name='Longitud')),
                ('centrolog', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro Logístico')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.gruposervicio', verbose_name='Grupo Servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.servicios', verbose_name='Servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.tiposervicio', verbose_name='Tipo de Servicio')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.ubicacion', verbose_name='Ubicación')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
