# Generated by Django 5.1.7 on 2025-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0007_agregarservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrologistico',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='grupoclientes',
            name='grupocliente',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Grupo'),
        ),
    ]
