# Generated by Django 5.0.13 on 2025-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0008_alter_centrologistico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrologistico',
            options={'ordering': ['id'], 'verbose_name': 'Centro Logístico', 'verbose_name_plural': 'Centros Logísticos'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='grupoclientes',
            options={'ordering': ['grupocliente'], 'verbose_name': 'Grupo Cliente', 'verbose_name_plural': 'Grupos Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicios'},
        ),
        migrations.AddField(
            model_name='agregarservicio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/unidades'),
        ),
    ]
