# Generated by Django 5.0.13 on 2025-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0009_alter_centrologistico_options_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrologistico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/centros'),
        ),
    ]
