# Generated by Django 5.0.13 on 2025-04-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0010_centrologistico_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposervicio',
            options={'ordering': ['grupo'], 'verbose_name': 'Grupo de Servicio', 'verbose_name_plural': 'Grupos de Servicios'},
        ),
        migrations.AlterField(
            model_name='agregarservicio',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad_cl.gruposervicio', verbose_name='Grupo de Servicio'),
        ),
    ]
