# Generated by Django 5.0.13 on 2025-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad_cl', '0011_alter_gruposervicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregarservicio',
            name='latitud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='agregarservicio',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitud'),
        ),
    ]
